"""Stage 10 — LaTeX table fragments for the lecture deck.

Two tables, both written to tables/ as \\input-able fragments so no number on a slide is
typed by hand:

  backtest_SPX.tex          the headline table, nine models on the S&P 500
  backtest_all_assets.tex   the same battery on all five assets, breaches and rate

The five-asset table exists to answer the obvious question about the headline one: does
the S&P result replicate, or is it one market's accident? A model is scored only on the
dates it actually covers, and n is printed whenever it differs from the full span.

Usage:  python src/10_slide_tables.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "notebook"))
from labcommon import ALPHA, ASSETS, LAB, PRECOMP, TABLES  # noqa: E402
import aidalab as al  # noqa: E402

LLM_MODEL = "claude-haiku-4-5"
OPEN_MODEL = "Qwen2.5-1.5B-Instruct"

# Which model produced a row is part of the result, so the label says so rather than
# "LLM" or "Open": a reader of the table alone should not have to ask.
COMMERCIAL = "Claude Haiku 4.5"
OPEN = "Qwen2.5-1.5B"

# Row order is the reading order of the headline table: benchmarks, then pretrained,
# then the commercial language model, then the open one a student runs.
ROWS = [
    ("NN-t", r"Neural volatility $+\,t$ tail"),
    ("GARCH-t", r"GARCH(1,1)-$t$"),
    ("HS", "Historical simulation"),
    ("Chronos-T5", "Chronos-T5, 500 sample paths"),
    ("LLM-dated+news", COMMERCIAL + r", dated $+$ headlines"),
    ("LLM-series+state", COMMERCIAL + r", series $+$ state"),
    ("LLM-dated", COMMERCIAL + ", dated (control)"),
    ("LLM-series", COMMERCIAL + ", series only"),
    ("Open-1.5B", r"\textbf{" + OPEN + r", asked}"),
    ("LLMTime-1.5B", r"\textbf{" + OPEN + r", sampled 1000$\times$}"),
]


def usable(d):
    m = d["raw_ok"] & d["sign_ok"]
    return (m & d["order_ok"]) if "order_ok" in d else m


def models_for(asset):
    """Every forecast available for one asset, on that asset's own test span."""
    b = pd.read_csv(LAB / f"bench_{asset}.csv", parse_dates=["date"])
    b = b[np.isclose(b["level"], ALPHA)]
    piv = b.pivot_table(index="date", columns="model", values="var")
    ret = b.groupby("date")["ret"].first()

    m = {k: piv[k] for k in ("HS", "GARCH-t", "NN-t") if k in piv}

    p = PRECOMP / f"chronos_t5_{asset}.csv"
    if p.exists():
        t5 = pd.read_csv(p, parse_dates=["date"])
        m["Chronos-T5"] = t5[np.isclose(t5["level"], ALPHA)].set_index("date")["var"]

    for cfg, key in [("series", "LLM-series"), ("series_state", "LLM-series+state"),
                     ("dated", "LLM-dated"), ("dated_news", "LLM-dated+news")]:
        f = PRECOMP / f"llm_{cfg}_{asset}_{LLM_MODEL}.csv"
        if f.exists():
            d = pd.read_csv(f, parse_dates=["date"]).set_index("date")
            m[key] = d.loc[usable(d), "var"]

    f = PRECOMP / f"local_series_{asset}_{OPEN_MODEL}.csv"
    if f.exists():
        d = pd.read_csv(f, parse_dates=["date"]).set_index("date")
        m["Open-1.5B"] = d.loc[usable(d), "var"]

    f = PRECOMP / f"llmtime_{asset}_{OPEN_MODEL}_T0.7_N1000_float16.csv"
    if f.exists():
        d = pd.read_csv(f, parse_dates=["date"]).set_index("date")
        m["LLMTime-1.5B"] = d.loc[usable(d), "var_01"]

    return ret, m


def tex(s):
    """Asset labels carry an ampersand (S&P 500), which is a column separator here."""
    return s.replace("&", r"\&")


def write(name, lines):
    out = TABLES / name
    out.write_text("\n".join(lines) + "\n")
    print(f"  -> tables/{name}")


def table_headline(asset="SPX"):
    """Nine models on one asset: breaches, rate, the two tests, and the loss."""
    ret, m = models_for(asset)
    bt = al.backtest_table(ret, m, alpha=ALPHA).set_index("model")
    rows = [k for k, _ in ROWS if k in bt.index]
    bt = bt.loc[rows].sort_values("pinball")

    L = [r"% generated by src/10_slide_tables.py -- do not edit",
         r"\begin{tabular}{lrrrccc}", r"\toprule",
         r"Model & $n$ & Breaches & Rate (\%) & UC & IND & Pinball \\", r"\midrule"]
    label = dict(ROWS)
    for k, x in bt.iterrows():
        uc = "pass" if x["p_uc"] >= 0.05 else r"\textbf{reject}"
        ind = "pass" if x["p_ind"] >= 0.05 else r"\textbf{reject}"
        rate = f"{x['rate_pct']:.2f}"
        obs = f"{int(x['observed'])}"
        if x["p_uc"] < 0.05:
            rate, obs = rf"\textbf{{{rate}}}", rf"\textbf{{{obs}}}"
        L.append(f"{label[k]} & {int(x['n'])} & {obs} & {rate} & {uc} & {ind} & "
                 f"{x['pinball']:.4f} " + r"\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write(f"backtest_{asset}.tex", L)
    return bt


def table_all_assets():
    """The same battery on five markets. Cell: breaches, with the rate beneath."""
    per, spans = {}, {}
    for a in ASSETS:
        ret, m = models_for(a)
        if not m:
            continue
        per[a] = al.backtest_table(ret, m, alpha=ALPHA).set_index("model")
        spans[a] = len(ret)
    assets = [a for a in ASSETS if a in per]

    L = [r"% generated by src/10_slide_tables.py -- do not edit",
         r"\begin{tabular}{l" + "c" * len(assets) + "}", r"\toprule",
         "Model & " + " & ".join(tex(ASSETS[a]["label"]) for a in assets)
         + r" \\",
         r"\midrule"]
    label = dict(ROWS)
    for k, lab in ROWS:
        if not any(k in per[a].index for a in assets):
            continue
        cells = []
        for a in assets:
            if k not in per[a].index:
                cells.append("---")
                continue
            x = per[a].loc[k]
            c = f"{int(x['observed'])} ({x['rate_pct']:.1f}\\%)"
            if x["p_uc"] < 0.05:
                c = rf"\textcolor{{IDAred}}{{\textbf{{{c}}}}}"
            cells.append(c)
        L.append(f"{lab} & " + " & ".join(cells) + r" \\")
    L += [r"\midrule",
          "Days scored & " + " & ".join(str(spans[a]) for a in assets) + r" \\",
          "Breaches expected & " + " & ".join(f"{ALPHA * spans[a]:.0f}"
                                              for a in assets) + r" \\",
          r"\bottomrule", r"\end{tabular}"]
    write("backtest_all_assets.tex", L)

    rej = {a: int((per[a]["p_uc"] < 0.05).sum()) for a in assets}
    tot = {a: len(per[a]) for a in assets}
    print("\n  rejected by Kupiec, per asset:")
    for a in assets:
        print(f"    {ASSETS[a]['label']:<14} {rej[a]} of {tot[a]}")
    return per, rej, tot


if __name__ == "__main__":
    TABLES.mkdir(parents=True, exist_ok=True)
    print("headline table")
    table_headline("SPX")
    print("\nfive-asset table")
    per, rej, tot = table_all_assets()

    facts = {"tbl_assets": len(rej),
             "tbl_rejected_total": sum(rej.values()),
             "tbl_models_total": sum(tot.values())}
    for a, n in rej.items():
        facts[f"tbl_rejected_{a}"] = n
    pd.Series(facts, dtype=object).rename("value").rename_axis("fact") \
        .to_csv(PRECOMP / "slide_facts_tables.csv")
    print(f"\n  facts -> slide_facts_tables.csv  {facts}")
