"""Stage 10 — LaTeX table fragments for the lecture deck.

Two tables, both written to tables/ as \\input-able fragments so no number on a slide is
typed by hand:

  backtest_SPX.tex          the headline table, nine models on the S&P 500
  backtest_all_assets.tex   the same battery on all five assets, breaches and rate

The five-asset table exists to answer the obvious question about the headline one: does
the S&P result replicate, or is it one market's accident? A model is scored only on the
dates it actually covers, and n is printed whenever it differs from the full span.

Usage:  python src/10_slide_tables.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "notebook"))
from labcommon import ALPHA, ASSETS, LAB, PRECOMP, TABLES  # noqa: E402
import aidalab as al  # noqa: E402

LLM_MODEL = "claude-haiku-4-5"
OPEN_MODEL = "Qwen2.5-1.5B-Instruct"

# Which model produced a row is part of the result, so the label says so rather than
# "LLM" or "Open": a reader of the table alone should not have to ask.
COMMERCIAL = "Claude Haiku 4.5"
OPEN = "Qwen2.5-1.5B"

# Row order is the reading order of the headline table: benchmarks, then pretrained,
# then the commercial language model, then the open one a student runs.
ROWS = [
    ("NN-t", r"Neural volatility $+\,t$ tail"),
    ("GARCH-t", r"GARCH(1,1)-$t$"),
    ("HS", "Historical simulation"),
    ("Chronos-T5", "Chronos-T5, 500 sample paths"),
    ("LLM-dated+news", COMMERCIAL + r", dated $+$ headlines"),
    ("LLM-series+state", COMMERCIAL + r", series $+$ state"),
    ("LLM-dated", COMMERCIAL + ", dated (control)"),
    ("LLM-series", COMMERCIAL + ", series only"),
    ("Open-1.5B", r"\textbf{" + OPEN + r", asked}"),
    ("LLMTime-1.5B", r"\textbf{" + OPEN + r", sampled 1000$\times$}"),
]


# What each scored model reads, and where its quantile comes from. Scale and shape are
# one column here: they part company only for the three estimated models, and repeating
# "pretrained" twice across seven rows says nothing the single column does not.
# The "reads" entries name the actual contents of the prompt or the input array. The
# four Claude rows differ only in what is added to the same return history, so they are
# written as increments; spelling them out here means the table does not depend on the
# configuration vocabulary Act IV introduces.
WHAT = {
    "HS":               ("Sorted window",      "The window itself"),
    "GARCH-t":          ("Returns",            r"Variance recursion, $t$ tail"),
    "NN-t":             ("7 predictors",       r"Neural volatility, $t$ tail"),
    "Chronos-T5":       ("Price levels",       "Pretrained weights"),
    "LLM-series":       ("Returns as text",    "Pretrained weights"),
    "LLM-series+state": (r"$+$ volatility, drawdown, HS VaR", "Pretrained weights"),
    "LLM-dated":        (r"$+$ asset name and date", "Pretrained weights"),
    "LLM-dated+news":   (r"$+$ date and headlines", "Pretrained weights"),
    "Open-1.5B":        ("Returns as text",    "Pretrained weights"),
    "LLMTime-1.5B":     ("Returns as text",    "Pretrained weights"),
}


def table_models(asset="SPX"):
    """One table naming every scored model, what it reads, and where its quantile comes from."""
    ret, m = models_for(asset)
    bt = al.backtest_table(ret, m, alpha=ALPHA).set_index("model")
    L = [r"% generated by src/10_slide_tables.py -- do not edit",
         r"\begin{tabular}{@{}L{4.5cm}L{4.1cm}L{3.9cm}@{}}", r"\toprule",
         r"\textbf{Model} & \textbf{Reads} & "
         r"\textbf{Quantile comes from} \\", r"\midrule"]
    # the leaderboard's names are too long for a three-column table
    short = {"LLM-dated+news": COMMERCIAL + r", dated $+$ news",
             "Chronos-T5": "Chronos-T5, 500 paths"}
    # Blue where the quantile is estimated on our training data, red where it arrives
    # pretrained. Same convention as the dataset figure on the previous frame.
    ESTIMATED = ("HS", "GARCH-t", "NN-t")
    for k, lab in ROWS:
        if k not in bt.index or k not in WHAT:
            continue
        lab = short.get(k, lab)
        inp, how = WHAT[k]
        tint = r"\trained" if k in ESTIMATED else r"\untrained"
        if k in ("Chronos-T5", "LLM-dated+news", "Open-1.5B"):
            L.append(r"\addlinespace[1pt]")
        L.append(f"{tint}{{{lab}}} & {inp} & {tint}{{{how}}} " + r"\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("models_used.tex", L)
    return {"models_listed": sum(1 for k, _ in ROWS if k in bt.index and k in WHAT)}


def usable(d):
    m = d["raw_ok"] & d["sign_ok"]
    return (m & d["order_ok"]) if "order_ok" in d else m


def models_for(asset):
    """Every forecast available for one asset, on that asset's own test span."""
    b = pd.read_csv(LAB / f"bench_{asset}.csv", parse_dates=["date"])
    b = b[np.isclose(b["level"], ALPHA)]
    piv = b.pivot_table(index="date", columns="model", values="var")
    ret = b.groupby("date")["ret"].first()

    m = {k: piv[k] for k in ("HS", "GARCH-t", "NN-t") if k in piv}

    p = PRECOMP / f"chronos_t5_{asset}.csv"
    if p.exists():
        t5 = pd.read_csv(p, parse_dates=["date"])
        m["Chronos-T5"] = t5[np.isclose(t5["level"], ALPHA)].set_index("date")["var"]

    for cfg, key in [("series", "LLM-series"), ("series_state", "LLM-series+state"),
                     ("dated", "LLM-dated"), ("dated_news", "LLM-dated+news")]:
        f = PRECOMP / f"llm_{cfg}_{asset}_{LLM_MODEL}.csv"
        if f.exists():
            d = pd.read_csv(f, parse_dates=["date"]).set_index("date")
            m[key] = d.loc[usable(d), "var"]

    f = PRECOMP / f"local_series_{asset}_{OPEN_MODEL}.csv"
    if f.exists():
        d = pd.read_csv(f, parse_dates=["date"]).set_index("date")
        m["Open-1.5B"] = d.loc[usable(d), "var"]

    f = PRECOMP / f"llmtime_{asset}_{OPEN_MODEL}_T0.7_N1000_float16.csv"
    if f.exists():
        d = pd.read_csv(f, parse_dates=["date"]).set_index("date")
        m["LLMTime-1.5B"] = d.loc[usable(d), "var_01"]

    return ret, m


def tex(s):
    """Asset labels carry an ampersand (S&P 500), which is a column separator here."""
    return s.replace("&", r"\&")


def write(name, lines):
    out = TABLES / name
    out.write_text("\n".join(lines) + "\n")
    print(f"  -> tables/{name}")


def table_headline(asset="SPX"):
    """Nine models on one asset: breaches, rate, the two tests, and the loss."""
    ret, m = models_for(asset)
    bt = al.backtest_table(ret, m, alpha=ALPHA).set_index("model")
    rows = [k for k, _ in ROWS if k in bt.index]
    bt = bt.loc[rows].sort_values("pinball")

    # A ranking without a test on the loss differential is an ordering, not a finding:
    # the deck insists on that two frames earlier, so the table carries the test. Every
    # model is compared with GARCH-t, the benchmark the others have to beat.
    REF = "GARCH-t"
    dm = {}
    for k in bt.index:
        if k == REF or REF not in m:
            continue
        _, pv, dd, _, _ = al.dm_test(ret, m[k], m[REF], alpha=ALPHA)
        dm[k] = (dd, pv)

    L = [r"% generated by src/10_slide_tables.py -- do not edit",
         r"\begin{tabular}{lrrrcccr}", r"\toprule",
         r"Model & $n$ & Breaches & Rate (\%) & UC & IND & Pinball & "
         r"DM vs GARCH \\", r"\midrule"]
    label = dict(ROWS)
    for k, x in bt.iterrows():
        # the verdict is the point of the table, so it carries colour rather than weight
        uc = r"\vpass" if x["p_uc"] >= 0.05 else r"\vreject"
        ind = r"\vpass" if x["p_ind"] >= 0.05 else r"\vreject"
        rate = f"{x['rate_pct']:.2f}"
        obs = f"{int(x['observed'])}"
        if x["p_uc"] < 0.05:
            rate, obs = rf"\textbf{{{rate}}}", rf"\textbf{{{obs}}}"
        if k == REF:
            cell = r"\textit{reference}"
        else:
            dd, pv = dm[k]
            cell = (rf"\textbf{{{pv:.3f}}}" if pv < 0.05 else f"{pv:.2f}")
        L.append(f"{label[k]} & {int(x['n'])} & {obs} & {rate} & {uc} & {ind} & "
                 f"{x['pinball']:.4f} & {cell} " + r"\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write(f"backtest_{asset}.tex", L)
    sep = sum(1 for _, pv in dm.values() if pv < 0.05)
    print(f"    separable from {REF} at 5%: {sep} of {len(dm)}")
    bt.attrs["dm_separable"] = sep
    bt.attrs["dm_compared"] = len(dm)
    return bt


def write_prompt():
    """Put the ACTUAL prompt on a slide, read out of 03_llm_lab.py rather than retyped.

    The deck argues that the prompt is a modelling decision and that the schema is what
    makes a reply checkable. Both claims are about a specific string, so the string
    belongs in the deck -- and it is parsed out of the source, so it cannot drift from
    the run that produced precomputed/.
    """
    import ast
    src = (Path(__file__).resolve().parent / "03_llm_lab.py").read_text()
    tree = ast.parse(src)
    got = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name in ("SYSTEM", "SCHEMA_TEXT", "CONTEXT_DAYS"):
                try:
                    got[name] = ast.literal_eval(node.value)
                except ValueError:
                    pass
    missing = {"SYSTEM", "SCHEMA_TEXT"} - set(got)
    if missing:
        print(f"  skip prompt fragment: {missing} not found in 03_llm_lab.py")
        return {}

    import textwrap
    sysrap = "\n".join(textwrap.wrap(got["SYSTEM"], 92))
    (TABLES / "llm_system.txt").write_text(sysrap + "\n")
    (TABLES / "llm_schema.txt").write_text(got["SCHEMA_TEXT"].strip() + "\n")

    # The system message and the schema are only the frame around the prompt. The
    # message the model actually receives is built by build_prompt(), so it is built
    # here the same way, on a real date, and elided only in the middle of the number
    # line. Anything else would put a paraphrase on a slide titled "verbatim".
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "llm03", Path(__file__).resolve().parent / "03_llm_lab.py")
    llm03 = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(llm03)

    r = pd.read_csv(LAB / "returns_SPX.csv", parse_dates=["date"]).set_index("date")["ret"]
    b = pd.read_csv(LAB / "bench_SPX.csv", parse_dates=["date"])
    d0 = b["date"].min()
    hist = r.loc[:d0].iloc[:-1].dropna()
    user = llm03.build_prompt("series", hist)
    body = user.split(got["SCHEMA_TEXT"])[0].rstrip()      # schema is shown separately
    lines = []
    for ln in body.splitlines():
        if len(ln) > 96:                                    # the serialised return line
            head = ln[:70].rsplit(",", 1)[0]
            tail = ln[-24:].split(",", 1)[-1].strip()
            ln = f"{head}, ...  ...,  {tail}"
        lines.append(ln)
    (TABLES / "llm_user.txt").write_text("\n".join(lines).rstrip() + "\n")
    print("  -> tables/llm_system.txt, llm_user.txt, llm_schema.txt")

    # The published sampling prompt, transcribed from models/gpt.py in
    # github.com/QuantLet/LLM_Risk, retrieved 2026-08-15. It is NOT generated from our
    # code, because our stage 09 does not reproduce it: see the note written beside it.
    published = (
        "SYSTEM\n"
        "You are a helpful assistant that performs time series predictions. The\n"
        "user will provide a sequence and you will predict the remaining sequence.\n"
        "The sequence is represented by decimal strings separated by commas.\n"
        "\nUSER\n"
        "Please continue the following sequence without producing any additional\n"
        "text. Do not say anything like 'the next terms in the sequence are', just\n"
        "return the numbers. Sequence:\n")
    (TABLES / "published_sampling_prompt.txt").write_text(published)
    print("  -> tables/published_sampling_prompt.txt")

    # Our open-weights leg sends the series with no wrapper at all: the prompt IS the
    # series. That is a deviation from the published protocol, and the slide says so.
    # Building it here, from the same serialiser stage 09 uses, keeps the contrast on
    # the slide honest rather than illustrative.
    src9 = (Path(__file__).resolve().parent / "09_llmtime.py").read_text()
    assert 'return ", ".join(f"{v:.2f}" for v in x)' in src9, \
        "09_llmtime.py serialiser changed; the sampling prompt on the slide would drift"
    r = pd.read_csv(LAB / "returns_SPX.csv", parse_dates=["date"])["ret"].dropna()
    ctx = r.iloc[-got.get("CONTEXT_DAYS", 60):].values
    line = ", ".join(f"{v:.2f}" for v in ctx) + ","
    shown = line[:104].rsplit(",", 1)[0] + ", ..."
    (TABLES / "llmtime_prompt.txt").write_text(shown + "\n")
    print("  -> tables/llmtime_prompt.txt")

    return {"prompt_context_days": got.get("CONTEXT_DAYS"),
            "prompt_schema_fields": got["SCHEMA_TEXT"].count("//"),
            "prompt_system_chars": len(got["SYSTEM"]),
            "sampling_prompt_has_instruction": 0}


def table_all_assets():
    """The same battery on five markets. Cell: breaches, with the rate beneath."""
    per, spans = {}, {}
    for a in ASSETS:
        ret, m = models_for(a)
        if not m:
            continue
        per[a] = al.backtest_table(ret, m, alpha=ALPHA).set_index("model")
        spans[a] = len(ret)
    assets = [a for a in ASSETS if a in per]

    L = [r"% generated by src/10_slide_tables.py -- do not edit",
         r"\begin{tabular}{l" + "c" * len(assets) + "}", r"\toprule",
         "Model & " + " & ".join(tex(ASSETS[a]["label"]) for a in assets)
         + r" \\",
         r"\midrule"]
    label = dict(ROWS)
    for k, lab in ROWS:
        if not any(k in per[a].index for a in assets):
            continue
        cells = []
        for a in assets:
            if k not in per[a].index:
                cells.append("---")
                continue
            x = per[a].loc[k]
            c = f"{int(x['observed'])} ({x['rate_pct']:.1f}\\%)"
            if x["p_uc"] < 0.05:
                c = rf"\textcolor{{IDAred}}{{\textbf{{{c}}}}}"
            cells.append(c)
        L.append(f"{lab} & " + " & ".join(cells) + r" \\")
    # No "Days scored" footer. Every model is scored on the dates it actually covers,
    # so n varies by model AND by asset -- a single row per column would claim all ten
    # cells in that column rest on the same sample, which for the two models that drop
    # structurally invalid replies is false. The exceptions are named in a note instead,
    # and the note is generated so it cannot fall out of date with the data.
    L += [r"\bottomrule", r"\end{tabular}"]
    write("backtest_all_assets.tex", L)

    short = {}
    for a in assets:
        for k in per[a].index:
            n = int(per[a].loc[k, "n"])
            if n < spans[a]:
                short.setdefault(k, []).append((tex(ASSETS[a]["label"]), n))
    def _join(xs):
        return xs[0] if len(xs) == 1 else ", ".join(xs[:-1]) + " and " + xs[-1]

    if short:
        # The affected cells carry their own n in the table, so the note states the rule
        # rather than reciting the counts back.
        note = (f"Every cell rests on {max(spans.values())} scored days, except where "
                "structurally invalid replies were dropped. Each test uses its own $n$.")
    else:
        note = (f"Every cell rests on {max(spans.values())} scored days, "
                f"{ALPHA * max(spans.values()):.0f} breaches expected.")
    write("backtest_all_assets_note.tex", [note])

    rej = {a: int((per[a]["p_uc"] < 0.05).sum()) for a in assets}
    tot = {a: len(per[a]) for a in assets}
    print("\n  rejected by Kupiec, per asset:")
    for a in assets:
        print(f"    {ASSETS[a]['label']:<14} {rej[a]} of {tot[a]}")
    return per, rej, tot


if __name__ == "__main__":
    TABLES.mkdir(parents=True, exist_ok=True)
    print("headline table")
    table_headline("SPX")
    print("\nfive-asset table")
    per, rej, tot = table_all_assets()

    print("\nthe model table")
    table_models("SPX")

    print("\nthe prompt, read out of 03_llm_lab.py")
    write_prompt()

    facts = {"tbl_assets": len(rej),
             "tbl_rejected_total": sum(rej.values()),
             "tbl_models_total": sum(tot.values())}
    for a, n in rej.items():
        facts[f"tbl_rejected_{a}"] = n
    pd.Series(facts, dtype=object).rename("value").rename_axis("fact") \
        .to_csv(PRECOMP / "slide_facts_tables.csv")
    print(f"\n  facts -> slide_facts_tables.csv  {facts}")
